title: This is D3etMe4n's Playground
description: He have nothing to do with his life so he made this.
theme: just-the-docs

url: https://d3etme4n.github.io/

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://github.com/D3etMe4n/D3etMe4n.github.io
